export interface SurahInfo {
  transliteration: string
  english: string
  revelation: "mecquoise" | "médinoise"
}

export const SURAH_META: Record<number, SurahInfo> = {
  1:   { transliteration: "Al-Fatiha",       english: "The Opening",           revelation: "mecquoise" },
  2:   { transliteration: "Al-Baqara",        english: "The Cow",               revelation: "médinoise" },
  3:   { transliteration: "Ali 'Imran",       english: "Family of Imran",       revelation: "médinoise" },
  4:   { transliteration: "An-Nisa",          english: "The Women",             revelation: "médinoise" },
  5:   { transliteration: "Al-Ma'ida",        english: "The Table Spread",      revelation: "médinoise" },
  6:   { transliteration: "Al-An'am",         english: "The Cattle",            revelation: "mecquoise" },
  7:   { transliteration: "Al-A'raf",         english: "The Heights",           revelation: "mecquoise" },
  8:   { transliteration: "Al-Anfal",         english: "The Spoils of War",     revelation: "médinoise" },
  9:   { transliteration: "At-Tawba",         english: "The Repentance",        revelation: "médinoise" },
  10:  { transliteration: "Yunus",            english: "Jonah",                 revelation: "mecquoise" },
  11:  { transliteration: "Hud",              english: "Hud",                   revelation: "mecquoise" },
  12:  { transliteration: "Yusuf",            english: "Joseph",                revelation: "mecquoise" },
  13:  { transliteration: "Ar-Ra'd",          english: "The Thunder",           revelation: "médinoise" },
  14:  { transliteration: "Ibrahim",          english: "Abraham",               revelation: "mecquoise" },
  15:  { transliteration: "Al-Hijr",          english: "The Rocky Tract",       revelation: "mecquoise" },
  16:  { transliteration: "An-Nahl",          english: "The Bee",               revelation: "mecquoise" },
  17:  { transliteration: "Al-Isra",          english: "The Night Journey",     revelation: "mecquoise" },
  18:  { transliteration: "Al-Kahf",          english: "The Cave",              revelation: "mecquoise" },
  19:  { transliteration: "Maryam",           english: "Mary",                  revelation: "mecquoise" },
  20:  { transliteration: "Ta-Ha",            english: "Ta-Ha",                 revelation: "mecquoise" },
  21:  { transliteration: "Al-Anbiya",        english: "The Prophets",          revelation: "mecquoise" },
  22:  { transliteration: "Al-Hajj",          english: "The Pilgrimage",        revelation: "médinoise" },
  23:  { transliteration: "Al-Mu'minun",      english: "The Believers",         revelation: "mecquoise" },
  24:  { transliteration: "An-Nur",           english: "The Light",             revelation: "médinoise" },
  25:  { transliteration: "Al-Furqan",        english: "The Criterion",         revelation: "mecquoise" },
  26:  { transliteration: "Ash-Shu'ara",      english: "The Poets",             revelation: "mecquoise" },
  27:  { transliteration: "An-Naml",          english: "The Ant",               revelation: "mecquoise" },
  28:  { transliteration: "Al-Qasas",         english: "The Stories",           revelation: "mecquoise" },
  29:  { transliteration: "Al-Ankabut",       english: "The Spider",            revelation: "mecquoise" },
  30:  { transliteration: "Ar-Rum",           english: "The Romans",            revelation: "mecquoise" },
  31:  { transliteration: "Luqman",           english: "Luqman",                revelation: "mecquoise" },
  32:  { transliteration: "As-Sajda",         english: "The Prostration",       revelation: "mecquoise" },
  33:  { transliteration: "Al-Ahzab",         english: "The Combined Forces",   revelation: "médinoise" },
  34:  { transliteration: "Saba",             english: "Sheba",                 revelation: "mecquoise" },
  35:  { transliteration: "Fatir",            english: "Originator",            revelation: "mecquoise" },
  36:  { transliteration: "Ya-Sin",           english: "Ya-Sin",                revelation: "mecquoise" },
  37:  { transliteration: "As-Saffat",        english: "Those Ranged in Ranks", revelation: "mecquoise" },
  38:  { transliteration: "Sad",              english: "The Letter Sad",        revelation: "mecquoise" },
  39:  { transliteration: "Az-Zumar",         english: "The Groups",            revelation: "mecquoise" },
  40:  { transliteration: "Ghafir",           english: "The Forgiver",          revelation: "mecquoise" },
  41:  { transliteration: "Fussilat",         english: "Explained in Detail",   revelation: "mecquoise" },
  42:  { transliteration: "Ash-Shuraa",       english: "The Consultation",      revelation: "mecquoise" },
  43:  { transliteration: "Az-Zukhruf",       english: "The Ornaments of Gold", revelation: "mecquoise" },
  44:  { transliteration: "Ad-Dukhan",        english: "The Smoke",             revelation: "mecquoise" },
  45:  { transliteration: "Al-Jathiya",       english: "The Crouching",         revelation: "mecquoise" },
  46:  { transliteration: "Al-Ahqaf",         english: "The Wind-Curved Sandhills", revelation: "mecquoise" },
  47:  { transliteration: "Muhammad",         english: "Muhammad",              revelation: "médinoise" },
  48:  { transliteration: "Al-Fath",          english: "The Victory",           revelation: "médinoise" },
  49:  { transliteration: "Al-Hujurat",       english: "The Rooms",             revelation: "médinoise" },
  50:  { transliteration: "Qaf",              english: "The Letter Qaf",        revelation: "mecquoise" },
  51:  { transliteration: "Adh-Dhariyat",     english: "The Winnowing Winds",   revelation: "mecquoise" },
  52:  { transliteration: "At-Tur",           english: "The Mount",             revelation: "mecquoise" },
  53:  { transliteration: "An-Najm",          english: "The Star",              revelation: "mecquoise" },
  54:  { transliteration: "Al-Qamar",         english: "The Moon",              revelation: "mecquoise" },
  55:  { transliteration: "Ar-Rahman",        english: "The Beneficent",        revelation: "mecquoise" },
  56:  { transliteration: "Al-Waqi'a",        english: "The Inevitable",        revelation: "mecquoise" },
  57:  { transliteration: "Al-Hadid",         english: "The Iron",              revelation: "médinoise" },
  58:  { transliteration: "Al-Mujadila",      english: "The Pleading Woman",    revelation: "médinoise" },
  59:  { transliteration: "Al-Hashr",         english: "The Exile",             revelation: "médinoise" },
  60:  { transliteration: "Al-Mumtahana",     english: "She that is Examined",  revelation: "médinoise" },
  61:  { transliteration: "As-Saf",           english: "The Ranks",             revelation: "médinoise" },
  62:  { transliteration: "Al-Jumu'a",        english: "The Congregation",      revelation: "médinoise" },
  63:  { transliteration: "Al-Munafiqun",     english: "The Hypocrites",        revelation: "médinoise" },
  64:  { transliteration: "At-Taghabun",      english: "The Mutual Disillusion",revelation: "médinoise" },
  65:  { transliteration: "At-Talaq",         english: "The Divorce",           revelation: "médinoise" },
  66:  { transliteration: "At-Tahrim",        english: "The Prohibition",       revelation: "médinoise" },
  67:  { transliteration: "Al-Mulk",          english: "The Sovereignty",       revelation: "mecquoise" },
  68:  { transliteration: "Al-Qalam",         english: "The Pen",               revelation: "mecquoise" },
  69:  { transliteration: "Al-Haqqa",         english: "The Reality",           revelation: "mecquoise" },
  70:  { transliteration: "Al-Ma'arij",       english: "The Ascending Stairways",revelation: "mecquoise" },
  71:  { transliteration: "Nuh",              english: "Noah",                  revelation: "mecquoise" },
  72:  { transliteration: "Al-Jinn",          english: "The Jinn",              revelation: "mecquoise" },
  73:  { transliteration: "Al-Muzzammil",     english: "The Enshrouded One",    revelation: "mecquoise" },
  74:  { transliteration: "Al-Muddaththir",   english: "The Cloaked One",       revelation: "mecquoise" },
  75:  { transliteration: "Al-Qiyama",        english: "The Resurrection",      revelation: "mecquoise" },
  76:  { transliteration: "Al-Insan",         english: "The Man",               revelation: "mecquoise" },
  77:  { transliteration: "Al-Mursalat",      english: "The Emissaries",        revelation: "mecquoise" },
  78:  { transliteration: "An-Naba",          english: "The Tidings",           revelation: "mecquoise" },
  79:  { transliteration: "An-Nazi'at",       english: "Those Who Drag Forth",  revelation: "mecquoise" },
  80:  { transliteration: "'Abasa",           english: "He Frowned",            revelation: "mecquoise" },
  81:  { transliteration: "At-Takwir",        english: "The Overthrowing",      revelation: "mecquoise" },
  82:  { transliteration: "Al-Infitar",       english: "The Cleaving",          revelation: "mecquoise" },
  83:  { transliteration: "Al-Mutaffifin",    english: "The Defrauding",        revelation: "mecquoise" },
  84:  { transliteration: "Al-Inshiqaq",      english: "The Sundering",         revelation: "mecquoise" },
  85:  { transliteration: "Al-Buruj",         english: "The Mansions of the Stars", revelation: "mecquoise" },
  86:  { transliteration: "At-Tariq",         english: "The Nightcomer",        revelation: "mecquoise" },
  87:  { transliteration: "Al-A'la",          english: "The Most High",         revelation: "mecquoise" },
  88:  { transliteration: "Al-Ghashiya",      english: "The Overwhelming",      revelation: "mecquoise" },
  89:  { transliteration: "Al-Fajr",          english: "The Dawn",              revelation: "mecquoise" },
  90:  { transliteration: "Al-Balad",         english: "The City",              revelation: "mecquoise" },
  91:  { transliteration: "Ash-Shams",        english: "The Sun",               revelation: "mecquoise" },
  92:  { transliteration: "Al-Layl",          english: "The Night",             revelation: "mecquoise" },
  93:  { transliteration: "Ad-Duha",          english: "The Morning Hours",     revelation: "mecquoise" },
  94:  { transliteration: "Ash-Sharh",        english: "The Relief",            revelation: "mecquoise" },
  95:  { transliteration: "At-Tin",           english: "The Fig",               revelation: "mecquoise" },
  96:  { transliteration: "Al-Alaq",          english: "The Clot",              revelation: "mecquoise" },
  97:  { transliteration: "Al-Qadr",          english: "The Power",             revelation: "mecquoise" },
  98:  { transliteration: "Al-Bayyina",       english: "The Clear Proof",       revelation: "médinoise" },
  99:  { transliteration: "Az-Zalzala",       english: "The Earthquake",        revelation: "médinoise" },
  100: { transliteration: "Al-Adiyat",        english: "The Courser",           revelation: "mecquoise" },
  101: { transliteration: "Al-Qari'a",        english: "The Calamity",          revelation: "mecquoise" },
  102: { transliteration: "At-Takathur",      english: "The Rivalry in World Increase", revelation: "mecquoise" },
  103: { transliteration: "Al-Asr",           english: "The Declining Day",     revelation: "mecquoise" },
  104: { transliteration: "Al-Humaza",        english: "The Traducer",          revelation: "mecquoise" },
  105: { transliteration: "Al-Fil",           english: "The Elephant",          revelation: "mecquoise" },
  106: { transliteration: "Quraysh",          english: "Quraysh",               revelation: "mecquoise" },
  107: { transliteration: "Al-Ma'un",         english: "The Small Kindnesses",  revelation: "mecquoise" },
  108: { transliteration: "Al-Kawthar",       english: "The Abundance",         revelation: "mecquoise" },
  109: { transliteration: "Al-Kafirun",       english: "The Disbelievers",      revelation: "mecquoise" },
  110: { transliteration: "An-Nasr",          english: "The Divine Support",    revelation: "médinoise" },
  111: { transliteration: "Al-Masad",         english: "The Palm Fibre",        revelation: "mecquoise" },
  112: { transliteration: "Al-Ikhlas",        english: "The Sincerity",         revelation: "mecquoise" },
  113: { transliteration: "Al-Falaq",         english: "The Daybreak",          revelation: "mecquoise" },
  114: { transliteration: "An-Nas",           english: "The Mankind",           revelation: "mecquoise" },
}
